### ISSUE TITLE
Basic installation instructions

### ISSUE THREAD

**Issue by andrasfuchs** [7m4mon/gr-ad2#1]
It would be great to have some basic installation instructions for beginners like me, who are new to GNU Radio.

I loaded the AnalogIn_Record flow graph in GNU Radio Companion, but there were some blocks missing.
![image](https://user-images.githubusercontent.com/910321/73932228-348dcc80-48da-11ea-8e72-30c157a36951.png)

My best guess is that I should be able to include the missing block using [the proper python script](https://github.com/7m4mon/gr-ad2/blob/master/gr-AD2_AnalogIn_Record/python/AD2_AnalogIn_Record_f.py), but I don't know how. Could you help me out (and include these instructions in [readme](https://github.com/7m4mon/gr-ad2/blob/master/README.md) if you think it's a good idea)?

**Comment by 7m4mon** [comment]
Thank you for your message,

## How to install (I'm using Ubuntsu and GRC 3.7.11 with WX GUI.)
   at "gr-AD2_AnalogXx_Xxxxxx" directory
   
   $ mkdir build ↵
   $ cd build ↵
   $ cmake ../ ↵
   $ make ↵
   $ sudo make install ↵

wxgui_.... blocks are not mine,  installed with GRC 3.7.11.

**Comment by andrasfuchs** [comment]
I used the following commands on both Ubuntu 19.10 and Raspbian with Raspberry Pi 3 B+, and the compilation was successful.

```
sudo apt install git cmake libboost-all-dev gnuradio doxygen python-pip
```

Downloaded Adept 2 Runtime .deb/Raspberry Pi installer from here:
https://reference.digilentinc.com/reference/software/adept/start

Downloaded .deb/ARM installer from here:
https://reference.digilentinc.com/reference/software/waveforms/waveforms-3/start

```
sudo dpkg -i digilent.adept.runtime.2.20.1_amd64.deb
sudo dpkg -i digilent.waveforms_3.12.2_amd64.deb
pip install dwf
```

```
git clone https://github.com/7m4mon/gr-ad2
cd gr-ad2/
cd gr-AD2_AnalogIn_Record/
mkdir build
cd build
cmake ../
make

sudo make install

gnuradio-companion
```

Opened 'AnalogIn_Record_FM_Demod.drc' and clicked Run/Execute.

The Ubuntu run failed in the end because it was running in a virtual machine and it had no access to local USB ports, and the Raspbian failed because of [a known problem with the Raspberry Pi 3 B+ USB driver](https://forum.digilentinc.com/topic/1713-analog-discovery-2-vs-raspberry-pi-3/).

I will try to make it work on Windows 10, but I'm sure the WX GUI Scope Sink in GNU Radio will fail, because that seems to be platform specific.

**Comment by andrasfuchs** [comment]
I installed Ubuntu 19.10 on a pendrive using Rufus + permanent storage.

I could install everything I mentioned before, and connected my AD2 to one of the USB ports.

When I run GRC 3.7.13.4 I got the following error in the log:

> Generating: '/home/ubuntu/Work/gr-ad2/top_block.py'
> Warning: This flow graph contains a throttle block and another rate limiting block, e.g. a hardware source or sink. This is usually undesired. Consider removing the throttle block.
> 
> Executing: /usr/bin/python2 -u /home/ubuntu/Work/gr-ad2/top_block.py
> 
> Warning: failed to XInitThreads()
> gr::log :INFO: audio source - Audio sink arch: alsa
> DWF Version: 3.12.2
> Traceback (most recent call last):
>   File "/home/ubuntu/Work/gr-ad2/top_block.py", line 145, in <module>
>     main()
>   File "/home/ubuntu/Work/gr-ad2/top_block.py", line 139, in main
>     tb = top_block_cls()
>   File "/home/ubuntu/Work/gr-ad2/top_block.py", line 85, in __init__
>     self.AD2_AnalogIn_Record_AD2_AnalogIn_Record_f_0 = AD2_AnalogIn_Record.AD2_AnalogIn_Record_f(0, 1.0, samp_rate, samp_rate)
>   File "/usr/local/lib/python2.7/dist-packages/AD2_AnalogIn_Record/AD2_AnalogIn_Record_f.py", line 30, in __init__
>     self.hdwf = dwf.Dwf(-1,1)   # 1:Scope Buffer Size 16k
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/dwf.py", line 1893, in __init__
>     hdwf = FDwfDeviceConfigOpen(idxDevice, idxCfg)
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/dwf.py", line 246, in _errcheck
>     raise DWFError(err.value, _mkstring(errmsg), (func, args))
> dwf.DWFError: ERROR(1): DptiIO failed ERC: 0x2
> DptiIO failed ERC: 0x2
> Communication after programming failed or image device id is wrong.
> ID: 0x0 Type: 0x0 Version: 0x0

Could you help me with this?

**Comment by 7m4mon** [comment]
I have never seen this error messeage.

I googled your error message, and I found this issue.
quoted from "https://forum.digilentinc.com/topic/2917-analog-discovery-waveforms-app-works-but-sdk-communication-fails/"

* The error shows that the dwf library and the device firmware versions are different, not compatible.
* The WaveForms Runtime consists of the dwf library and device firmware images. The firmware is programmed by the dwf library on device opening, when needed.
* I suppose you have included an older version of dwf library in your application and this takes the firmware from the newer installed WF Runtime. Make sure your application uses the dwf installed by the WF Runtime. On Windows this can be found in the system folder.

**Comment by andrasfuchs** [comment]
Even Waveforms had problems detecting the AD2 on Ubuntu (it worked fine on Windows 10). 
Then I plugged the AD2 into another USB port and, voila, it worked!

Now, I will try to somehow install your compiled python (.py, .pyc and .pyo) files under Windows. (The compiled python bytecode should be cross-platform.)

**Comment by andrasfuchs** [comment]
Alright, so there are several things that are different/problematic on Windows.

1, 
There is a GNURadio-specific python 2.7 installation in the `c:\Program Files\GNURadio-3.8\gr-python27\` folder. We need to install the `dwf` package there, but unfortunately the pre-compiled pip.exe is corrupt by default. 

To reinstall that, we need to execute this command:
`.\python.exe -m pip install --upgrade pip --force-reinstall`
This replaces the pip.exe in the `gr-python27\Scripts\` folder.

After this, we can run the following command in the `gr-python27\Scripts\` folder to install dwf:
`.\pip.exe install dwf`
This installs the necessary libraries for this gnuradio-specific python environment.

2, 
Python's folder structure on Windows is different from the one on Linux, so we need to copy the python files of this project (e.g. _init.py and AD2_AnalogIn_Record_f.py) into their proper subdirectories, like `c:\Program Files\GNURadio-3.8\gr-python27\lib\site-packages\AD2_AnalogIn_Record\`. (These files are copied into the `dist-packages` directory on Linux)

3, 
GNURadio 3.8 on Windows doesn't load the .xml block definitions, because they are considered deprecated. The current format is .yaml. The conversion isn't difficult, but manual work. I suggest to replace the current .xml files with their tree and block .yaml counterparts for future compatibility. (I can share my working versions if anyone is interested.)

4,
The Windows version of GNURadio doesn't have a WX renderer, only QT sinks work.
After starting the GNURadio Companion, you should see an error message telling you that the `wxgui_scopesink2` is not available. It needs to be replaced by the QT GUI Sink, to make it work.


After all these steps, this is how the working flow graph looks like on Windows:
![image](https://user-images.githubusercontent.com/910321/74591150-cd78c200-5015-11ea-927c-ddc497c8a599.png)

![image](https://user-images.githubusercontent.com/910321/74591277-dddd6c80-5016-11ea-9bfd-300285bf5934.png)

**Comment by 7m4mon** [comment]
That's great! I invited you to collaborators. If you have any improvements, please commit it freely.

**Comment by andrasfuchs** [comment]
Thanks, I'll start with the README, I will include the Windows-specific information in this thread, if that's ok with you.

**Comment by 7m4mon** [comment]
OK! please edit README or add new description file.
