### ISSUE TITLE
handler caught exception: global name 'fLost' is not defined

### ISSUE THREAD

**Issue by andrasfuchs** [7m4mon/gr-ad2#2]
I opened [AnalogIn_Record_FM_Demon.drc](https://github.com/7m4mon/gr-ad2/blob/master/AnalogIn_Record_FM_Demod.grc) on Ubuntu, and executed the flow graph in GRC.

> <<< Welcome to GNU Radio Companion 3.7.13.4 >>>
> 
> DWF Version: 3.12.2
> BufferSize 16384
> begin acquisition
> handler caught exception: global name 'fLost' is not defined
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 55, in eval
>     try: self._callback()
>   File "/usr/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 225, in __gr_block_handle
>     ) for i in range(noutputs)],
>   File "/usr/local/lib/python2.7/dist-packages/AD2_AnalogIn_Record/AD2_AnalogIn_Record_f.py", line 68, in work
>     print "fLost" + str(fLost)
> NameError: global name 'fLost' is not defined
> finished
> thread[thread-per-block[0]: <block AD2_AnalogIn_Record_f (16)>]: SWIG director method error. Error detected when calling 'feval_ll.eval'
> 
> (top_block.py:7703): Gtk-WARNING **: 08:50:44.879: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)
> 
> (top_block.py:7703): Gtk-WARNING **: 08:50:44.879: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)
> 
> >>> Done

**Comment by 7m4mon** [comment]
Thank you for your bug report.
I modified as follows:

    print "cLost" + str(cLost)
