### ISSUE TITLE
Devices are busy, used by other applications

### ISSUE THREAD

**Issue by andrasfuchs** [7m4mon/gr-ad2#3]
I opened [AnalogIn_Record_FM_Demon.drc](https://github.com/7m4mon/gr-ad2/blob/master/AnalogIn_Record_FM_Demod.grc) on Ubuntu, and executed the flow graph in GRC 3.7.13.4.

I could successfully execute the flow graph for a few times, then I got this error. No matter what I do, I keep getting this error until I fully restart the system.

> Generating: '/home/ubuntu/Work/gr-ad2/top_block.py'
> >>> Warning: This flow graph contains a throttle block and another rate limiting block, e.g. a hardware source or sink. This is usually undesired. Consider removing the throttle block.
> 
> Executing: /usr/bin/python2 -u /home/ubuntu/Work/gr-ad2/top_block.py
> 
> Warning: failed to XInitThreads()
> gr::log :INFO: audio source - Audio sink arch: alsa
> DWF Version: 3.12.2
> Traceback (most recent call last):
>   File "/home/ubuntu/Work/gr-ad2/top_block.py", line 178, in <module>
>     main()
>   File "/home/ubuntu/Work/gr-ad2/top_block.py", line 172, in main
>     tb = top_block_cls()
>   File "/home/ubuntu/Work/gr-ad2/top_block.py", line 110, in __init__
>     self.AD2_AnalogIn_Record_AD2_AnalogIn_Record_f_0 = AD2_AnalogIn_Record.AD2_AnalogIn_Record_f(0, 1.0, samp_rate, samp_rate)
>   File "/usr/local/lib/python2.7/dist-packages/AD2_AnalogIn_Record/AD2_AnalogIn_Record_f.py", line 30, in __init__
>     self.hdwf = dwf.Dwf(-1,1)   # 1:Scope Buffer Size 16k
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/dwf.py", line 1893, in __init__
>     hdwf = FDwfDeviceConfigOpen(idxDevice, idxCfg)
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/dwf.py", line 246, in _errcheck
>     raise DWFError(err.value, _mkstring(errmsg), (func, args))
> dwf.DWFError: ERROR(1): Devices are busy, used by other applications

**Comment by 7m4mon** [comment]
![do not abort x button](https://user-images.githubusercontent.com/11815644/74441468-3693f480-4eb3-11ea-9008-a86ad5918dc0.png)

I know this issue.
If you abort with not GUI 'x' button but 'kill' button, or stop with exception, you should restart GRC.

This is because the stop function is not called.

**Comment by andrasfuchs** [comment]
I didn't know that, thanks for the tip!
