### ISSUE TITLE
can this block output signal  in two channels synchronously

### ISSUE THREAD

**Issue by seuliang** [7m4mon/gr-ad2#8]
I just want to output one byte stream which has two effictive bits each byte into two channels with discovery2  in gnuradio.
these two bits need to be converted to heigh or low voltage at same time.
I want to know if this can be done with this porject.
or do you have any other device recommended rather than discovery2 that work with gnuradio?

with regards

**Comment by 7m4mon** [comment]
Hi seuliang,
Excuse me, but this project cannot output binary sequences.
Also, I don't know the device that can output bitstream continuously.
I'm sorry I can't help you.

Regards.

**Comment by seuliang** [comment]
Hi,7m4mon
that's ok. Thank you angway.

with regards
